"""initial commit.

Revision ID: c49df3e7fdb9
Revises: 
Create Date: 2022-01-17 14:43:51.955355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49df3e7fdb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_profile_sync', sa.Date(), nullable=True),
    sa.Column('last_friends_sync', sa.Date(), nullable=True),
    sa.Column('last_posts_sync', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_last_friends_sync'), 'profiles', ['last_friends_sync'], unique=False)
    op.create_index(op.f('ix_profiles_last_posts_sync'), 'profiles', ['last_posts_sync'], unique=False)
    op.create_index(op.f('ix_profiles_last_profile_sync'), 'profiles', ['last_profile_sync'], unique=False)
    op.create_index(op.f('ix_profiles_name'), 'profiles', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_name'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_last_profile_sync'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_last_posts_sync'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_last_friends_sync'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
